spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:prolocobe}
    username: ${POSTGRES_USER:prolocobe}
    password: ${POSTGRES_PASSWORD:prolocobe-dev}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

server:
  port: 8080
